### ISSUE TITLE
Some questions about major copy number and minor copy number?

### ISSUE THREAD

**Issue by Rickyzhang1990** [yuchaojiang/Canopy#1]
Dear Dr Jiang, I am very interesting in tumor clonal evolution analysis , but I was doubt about major copy number and minor copy number ,how can I get them from Mutect result ??Thank you!

**Comment by yuchaojiang** [comment]
Hi,

Thanks for your interest in Canopy. Mutect only outputs somatic point mutations. For allele-specific copy number (ASCN) estimates, we recommend Sequenza. After you call ASCN, you can refer to our GitHub page for how to further generate the major and minor copy numbers.

Best,
Yuchao

On Feb 22, 2017, at 3:33 AM, Rickyzhang1990 <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Dr Jiang, I am very interesting in tumor clonal evolution analysis , but I was doubt about major copy number and minor copy number ,how can I get them from Mutect result ??Thank you!

**Comment by Rickyzhang1990** [comment]
@yuchaojiang  thank you for your reply and I will read your method carefully
