### ISSUE TITLE
Selection of BIC

### ISSUE THREAD

**Issue by biobenkj** [yuchaojiang/Canopy#10]
Thanks for writing Canopy! 

I have a quick question regarding the selection of the number of subclones using the BIC. In the documentation it's written:

```
optK = K[which.max(bic)]
```

I'm a little confused because I would normally pick the most negative BIC as the model instead of a maximum (closer to 0). I probably have this backwards and would love to have some insight into this. Thanks again!

**Comment by yuchaojiang** [comment]
Thanks for your interest! Yes we used an “unconventional” BIC as 2*logL-k*log(n) which you would maximize instead of minimize.
________________________________

**Comment by biobenkj** [comment]
Ah, thanks!

I also should have just looked at the Google groups: https://groups.google.com/forum/#!searchin/canopy_phylogeny/BIC%7Csort:date/canopy_phylogeny/zuRFX7aU0q8/LXsnlrdpEgAJ

Thanks again!
