### ISSUE TITLE
 Error in Y[, -1] %*% C : requires numeric/complex matrix/vector arguments

### ISSUE THREAD

**Issue by baohua100** [yuchaojiang/Canopy#2]
Hi Yuchao,

I have some errors when I run Canopy:
I would appreciate if you can help on this:

K = 3:4
numchain= 20

> sampchain = canopy.sample(R = R, X = X, WM = WM, Wm = Wm, epsilonM = 0.1, epsilonm = 0.1, C=NULL, Y = Y, K = K, numchain = numchain, simrun = 50000, writeskip = 200, projectname = projectname, cell.line = FALSE, plot.likelihood = TRUE)

Sample in tree space with 3 subclones
        Running chain 1 out of 20 ...
**Error in Y[, -1] %*% C : requires numeric/complex matrix/vector arguments**

My input matrix is : 

> R
         Primary Metastasis
LILRB1        19         20
EXD1           0         31
KLK5          12          0
EXOC3L2       31         26
HIST1H3E      46         15
TJP3           0          6
DNAH17        38          0
TBC1D9        31         69
SCN9A         29         81
PIGL          66          0
BAI3          75         40
TNS1           0         49
SFTPA1         0         10
LGALS9B        0         27
PPP1R3A       22          0
ZFR          100          0
VN1R2         21         57
GATM          17          0
TOP2A         25          0
SLC30A8        0         20
SLC28A3       13         15
HOXB6          0         14

> X
         Primary Metastasis
LILRB1        31         51
EXD1          92        114
KLK5          58         45
EXOC3L2       57         30
HIST1H3E      69         41
TJP3          96         47
DNAH17       247        206
TBC1D9        91        136
SCN9A         89        120
PIGL         250         73
BAI3         136         80
TNS1         113         76
SFTPA1        51         40
LGALS9B      110         67
PPP1R3A       76         78
ZFR          172         28
VN1R2        121         98
GATM          55         63
TOP2A        248        182
SLC30A8       62         45
SLC28A3       59         47
HOXB6        100         80

> WM
        Primary Metastasis
chr10 0.9643512   1.327601
chr2  1.2086787   1.386094
chr14 1.2081759   1.346075
chr11 1.0514888   1.287871

> Wm
        Primary Metastasis
chr10 0.6027195 0.10620810
chr2  0.9459225 0.09648037
chr14 0.1208176 0.10768597
chr11 0.7974671 0.10732256

> Y
         non.cna_region chr10 chr2 chr14 chr11
LILRB1                1     0    0     0     0
EXD1                  1     0    0     0     0
KLK5                  1     0    0     0     0
EXOC3L2               1     0    0     0     0
HIST1H3E              1     0    0     0     0
TJP3                  1     0    0     0     0
DNAH17                1     0    0     0     0
TBC1D9                1     0    0     0     0
SCN9A                 1     0    0     0     0
PIGL                  1     0    0     0     0
BAI3                  1     0    0     0     0
TNS1                  1     0    0     0     0
SFTPA1                0     1    0     0     0
LGALS9B               1     0    0     0     0
PPP1R3A               1     0    0     0     0
ZFR                   1     0    0     0     0
VN1R2                 1     0    0     0     0
GATM                  1     0    0     0     0
TOP2A                 1     0    0     0     0
SLC30A8               1     0    0     0     0
SLC28A3               1     0    0     0     0
HOXB6                 1     0    0     0     0

**Comment by yuchaojiang** [comment]
Hi,

I guess you figured this out. Your Y matrix in your previous email/post isn't correct. It needs to contain all point mutations as rows.
