### ISSUE TITLE
How to generate CNA overlaps input

### ISSUE THREAD

**Issue by baohua100** [yuchaojiang/Canopy#3]
In the example dataset MDA231, there are 4 CNAs used as input, chr7,12,18,19.

In the C matrix:

         chr7_1 chr7_2 chr12_1 chr12_2 chr18 chr19
chr7       1      1       0       0     0     0
chr12      0      0       1       1     0     0
chr18      0      0       0       0     1     0
chr19      0      0       0       0     0     1

Here, what does chr_1 chr7_2 mean?

ALso, in one sample I have two segments overlapped with one segment in another sample

sample 1:
chr1:1-10000 (major 2.6, minor 0.3) ,   10005-20000 (major 2.03, minor 0.2)
sample 2:
chr1:1-20000 (major 2.7, minor 0.27)

How should I preprare the CNA WM, Wm and C matrix?

**Comment by yuchaojiang** [comment]
It means that for that region on chr7 we know that there are two overlapping CNA  events. See https://github.com/yuchaojiang/Canopy/blob/master/instruction/overlapping_CNA.md for more information.

Hope that this clarifies,
Yuchao


On Mar 14, 2017, at 3:55 PM, baohua100 <notifications@github.com<mailto:notifications@github.com>> wrote:


In the example dataset MDA231, there are 4 CNAs used as input, chr7,12,18,19.

In the C matrix:

     chr7_1 chr7_2 chr12_1 chr12_2 chr18 chr19


chr7 1 1 0 0 0 0
chr12 0 0 1 1 0 0
chr18 0 0 0 0 1 0
chr19 0 0 0 0 0 1

Here, what does chr_1 chr7_2 mean?
