### ISSUE TITLE
Error in 1:nrow(config.summary) : argument of length 0  using canopy.post

### ISSUE THREAD

**Issue by baohua100** [yuchaojiang/Canopy#4]
Hi Jiang,

I have run a real dataset from primary and metastasis samples by WES. I got an error when I run canopy.post().  Any thoughts regarding this problem? 

sampchain = canopy.sample(R = R, X = X, WM = WM, Wm = Wm, epsilonM = 0.02,
                          epsilonm = 0.02, C=C, Y = Y, K = K, numchain = numchain,
                          simrun = 50000, writeskip = 200, projectname = projectname,
                          cell.line = FALSE, plot.likelihood = TRUE)

save.image(file=paste(projectname,'.rda',sep=""))

burnin = 100
thin = 10
bic = canopy.BIC(sampchain = sampchain, projectname = projectname, K = K,
                 numchain = numchain, burnin = burnin, thin = thin, pdf = FALSE)

optK = K[which.max(bic)]

### The above code running OK!!!!

> post = canopy.post(sampchain = sampchain, projectname = projectname, K = K,
 numchain = numchain, burnin = burnin, thin = thin, optK = optK,
 C = C, post.config.cutoff = 0.05)

Error in 1:nrow(config.summary) : argument of length 0

#####
post = canopy.post(sampchain = sampchain, projectname = projectname, K = K,
                   numchain = numchain, burnin = burnin, thin = thin, optK = optK,
                   C = C, post.config.cutoff = 1)

Error in config.summary[i, 1] : subscript out of bounds

##### Input

[OS7_Y.txt](https://github.com/yuchaojiang/Canopy/files/845701/OS7_Y.txt)
[OS7_R.txt](https://github.com/yuchaojiang/Canopy/files/845704/OS7_R.txt)
[OS7_WM.txt](https://github.com/yuchaojiang/Canopy/files/845705/OS7_WM.txt)
[OS7_Wm.txt](https://github.com/yuchaojiang/Canopy/files/845702/OS7_Wm.txt)
[OS7_X.txt](https://github.com/yuchaojiang/Canopy/files/845703/OS7_X.txt)

**Comment by yuchaojiang** [comment]
In the MCMC sampling step you sampled 50000 times with write skip 200. As a result, your thinning 10 and burnin 100 doesnt leave you any posterior tree. You need to let the chain run long enough. The default parameters are recommended.
