### ISSUE TITLE
Ambiguous Input File Instructions

### ISSUE THREAD

**Issue by DarioS** [yuchaojiang/Canopy#6]
In the document SNA_CNA_input.md, two plots are shown but it's unclear which is for the normal sample and which is for tumour. Each plot should have a main title. Also, much of the discussion is about the curation recommended for Sequenza. Does Falcon have the same issues or is such curation not necessary for it? This paragraph could be reworded for clarifcation.

Elsewhere, there's a VAF scatterplot and heatmap for multiple samples of a patient, but no mention of how they are created. Is there a function in the package that generates these? Canopy depends on pheatmap, so I guess there is, but haven't been able to find it. Again, the documentation could be more explicit to better guide the end user.

**Comment by yuchaojiang** [comment]
Thanks for your comment and recommendation. The two plots you mentioned are both tumor samples, one primary tumor and the other relapse genome, as is mentioned in the document "The top panel is for the primary tumor and the bottom panel is for the relapse." I've added caption to both plots.

Yes, Falcon-X is also applied to primary tumor + normal and relapse + normal separately and further curation is needed.

Yes, it was generated using pheatmap or any heatmap drawing functions/packages. The document is updated. Thanks again.
