### ISSUE TITLE
More Realistic Vignette Example

### ISSUE THREAD

**Issue by DarioS** [yuchaojiang/Canopy#7]
The examples are based on the R, X, C, and Y matrices already being calculated and conveniently available as RData files, which is unrealistic. How are these variables created in the first place? The vignette doesn't provide enough detail to get started on a dataset consisting of BAM files. It also doesn't demonstrate the algorithm working directly on the output of Falcon, which is claimed by the journal article.

**Comment by yuchaojiang** [comment]
Thanks for your interest in Canopy and your earlier pull request. I've merged it to the master branch.

To get a clean set of SNA and CNA input for Canopy isn't trivial. Yet this is not the focus and major contribution of Canopy. To generate the SNA input from bam files, we use GATK UnifiedGenotyper with code available here https://github.com/yuchaojiang/Canopy/blob/master/instruction/UnifiedGenotyper.sh .
To generate the allele-specific CNA input, we claimed in our journal article both FalconX and Sequenza. These are two independent packages from Canopy. From our experience, Sequenza is fairly easy to run following their instructions. FalconX is also from our group and can be found via CRAN https://cran.r-project.org/web/packages/falconx/index.html . If you have questions with regard to that you can contact the maintainer Hao Chen <hxchen at ucdavis.edu>.

Details on how to generate and select SNA and CNA input can be found here https://github.com/yuchaojiang/Canopy/blob/master/instruction/SNA_CNA_input.md

**Comment by yuchaojiang** [comment]
BTW, thanks for your interest in Canopy and pull request! Let me know if you have more question.
