### ISSUE TITLE
Clustering with 1 Sample

### ISSUE THREAD

**Issue by jaebird123** [yuchaojiang/Canopy#8]
I have a single sample with around 325 single nucleotide alterations (SNAs) which I've stored in the `R` and `X` variables. I can use these with my CNA data to run `canopy.sample()` but when I run clustering in the following way
```
canopy.cluster(R = R,
               X = X,
               num_cluster = num_cluster,
               num_run = num_run)
```
I get the error
```
Error in while (diff > 0.001 || numiters <= 30) { : 
  missing value where TRUE/FALSE needed
```
Any reason why this might be? Thank you for your help!

**Comment by yuchaojiang** [comment]
Hi Jesse,

I just replied to another user with the same question yesterday. Please see below. Note that you need to update the package from GitHub. Canopy is not primarily designed for one sample  -- I’m not sure how much information about phylogeny you can get from one heterogeneous sample. Also Canopy is not focused on clustering, which is only a by-product of the program.

Thanks,
Yuchao
