### ISSUE TITLE
how to run my trees longer？

### ISSUE THREAD

**Issue by jamescjc123** [yuchaojiang/Canopy#9]
hi，
        When I run the program, I have a error like this: Error in config.summary[i, 1] : subscript out of bound.
        I see you suggest run my trees longer to get more accurate posterior evaluations(https://github.com/yuchaojiang/Canopy/blob/master/instruction/config_summary_error.md).
        And I want to know which parameter can make the trees run longer?
        Thank you!

**Comment by urrutiag** [comment]
Hi, thanks for your interest in Canopy.  min.simrun is the parameter to run the chain longer, that is, to add more trees.  I hope this addresses the error you are seeing.  Otherwise let me know and I can help further.
Gene

**Comment by jamescjc123** [comment]
Hi，thanks for helping me，I am very interested in Canopy. And I have another question,  when I read the paper about simulation step, i see the total read depth sampled from a multinomial distribution:
![x](https://user-images.githubusercontent.com/19986431/40401020-341a7766-5e77-11e8-94eb-934b6239dc2a.png)
I want to know what're the meaning of S and S'？

**Comment by yuchaojiang** [comment]
S is the number of somatic point mutations (‘  is comma not S prime). d is the average coverage for each point mutation

Sent from my iPhone

On May 22, 2018, at 10:51 PM, chaijinchao <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi，thanks for helping me，I am very interested in Canopy. And I have another question, when I read the paper about simulation step, i see the total read depth sampled from a multinomial distribution:
[x]<https://user-images.githubusercontent.com/19986431/40401020-341a7766-5e77-11e8-94eb-934b6239dc2a.png>
I want to know what's the meaning of S and S'？
